name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pypa/build
        run: |
          python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Test local distributions
        run: |
          pip install dist/sparselsh-*.tar.gz
          sparselsh MANIFEST
          pip uninstall sparselsh --yes
          pip install dist/sparselsh-*.whl
          sparselsh MANIFEST
          pip uninstall sparselsh --yes
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  pypi-publish:
    name: Upload Release to PyPI
    needs:
      - build
      - publish-to-testpypi
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download all distributions
      uses: actions/download-artifact@v4.1.7
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
